[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.wasm]
command = "cargo"
args = ["build", "--release","--target", "wasm32-unknown-unknown"]

[tasks.test]
workspace = false
command = "cargo"
args = ["test"]

[tasks.docs-test-clean]
workspace = false
command = "dune"
args = ["clean"]

[tasks.docs-test]
workspace = false
command = "dune"
args = ["runtest"]
dependencies = ["docs-test-clean", "wasm" ]

[tasks.doc]
workspace = false
command = "cargo"
args = ["doc", "--features", "testing", "--no-deps", "--target-dir", "public"]

[tasks.ci]
workspace = false
dependencies = [
    "fmt", # FIXME: do we need both fmt and fmt-check here?
    "fmt-check",
    "wasm",
    "docs-test",
    "test"
    # FIXME: re-enable these when they compile
    # "doc",
]
